# Generated by Django 5.2.1 on 2025-05-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composant',
            name='nom',
            field=models.CharField(max_length=300),
        ),
    ]
